# version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=http://localhost:3000
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    depends_on:
      - db
    volumes:
      - .:/app
  cron:
    build: .
    command: node dist/scripts/cron.js
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=staffly
    volumes:
      - postgres_data:/var/lib/postgresql/data

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx ts-node src/workers/email-worker.ts
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app

volumes:
  postgres_data:
