# version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=http://localhost:3000
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    volumes:
      - .:/app

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile.email-worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    volumes:
      - .:/app